### ISSUE TITLE
Looks like -importall has a problem

### ISSUE THREAD

**Issue by nonamebatbai** [amrshaheen61/UE4LocalizationsTool#10]
![image](https://user-images.githubusercontent.com/55612825/173164035-ba947f61-e6e1-44e9-9d70-0e05da09b779.png)
Looks like -importall has a problem or I'm not using it correctly. can you help me ?

**Comment by amrshaheen61** [comment]
i fixed it here
[v1.4](https://github.com/amrshaheen61/UE4LocalizationsTool/releases/tag/v1.4)
close the issue if your problem fixed

**Comment by amrshaheen61** [comment]
@nonamebatbai 
i fixed it here
[v1.4](https://github.com/amrshaheen61/UE4LocalizationsTool/releases/tag/v1.4)
close the issue if your problem fixed
