### ISSUE TITLE
Exportall function with a filter?

### ISSUE THREAD

**Issue by Mayki07** [amrshaheen61/UE4LocalizationsTool#11]
I would like to thank you for your work, it's a great help when translating games.
Would it be possible to add an exportall function with a filter? I would need to export only certain text from a lot of files.
Thank you for your reply.

![UE4](https://user-images.githubusercontent.com/35667524/173220735-fba5553d-c05d-4f10-b08e-5212a9f1e58b.jpg)

**Comment by amrshaheen61** [comment]
@Mayki07 
Ok 👍

**Comment by amrshaheen61** [comment]
@Mayki07 
Here https://github.com/amrshaheen61/UE4LocalizationsTool/releases/tag/v1.5

**Comment by Mayki07** [comment]
Excellent. Good work. Everything works as expected, I am very grateful to you. This will make my job of translating games a lot easier... 🥇

**Comment by amrshaheen61** [comment]
@Mayki07 
Right now no thank you 🌹
