### ISSUE TITLE
Texts not extracted

### ISSUE THREAD

**Issue by Saipan0** [amrshaheen61/UE4LocalizationsTool#13]
hello, first of all thank you for the previous problem.
Your update has been a success, It has worked wonderfully.

I have a problem with texts not being extracted / found by your program.
I am attaching the files so you can see. There are texts in .uexp which are not found in the uasset file .. 
or in any case they are not displayed. The problem persists in multiple files, the one I am attaching is one in general.

[File.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/8913984/File.zip)

can a solution be found?
thank's for your job

**Comment by amrshaheen61** [comment]
@Saipan0 
Right now can't parse function

**Comment by Saipan0** [comment]
> Right now can't parse function

OK thank you for answering me.

**Comment by TheDarkness1994** [comment]
@Saipan0 And you can send all the files with the text, I'll try to create a locres file for you. Well, or write the name of the game, I'll try to download all the files myself to make a locres file out of them, if possible.

**Comment by Saipan0** [comment]
> @Saipan0 And you can send all the files with the text, I'll try to create a locres file for you. Well, or write the name of the game, I'll try to download all the files myself to make a locres file out of them, if possible.

my question was more generally, because in more games it gave me this problem. here are the lyrics.
[text.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/8923461/text.zip)

--------------------------------------------------------------------------------------

@amrshaheen61  if for now the problem cannot be solved, do I close as not solved?

**Comment by TheDarkness1994** [comment]
@Saipan0 Send .uasset and .uexp files.

**Comment by TheDarkness1994** [comment]
@Saipan0 
[Translate.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/8923540/Translate.zip)
This locres file contains the same text that you were unable to extract. There will be questions write.
But it does not extract all the text, but it will still be easier to translate games.

I use this utility to create lores files:
https://github.com/VD42/UE4TextExtractor

**Comment by Saipan0** [comment]
> @Saipan0 [Translate.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/8923540/Translate.zip) This locres file contains the same text that you were unable to extract. There will be questions write. But it does not extract all the text, but it will still be easier to translate games.

okok, thanks, I'll try and let you know.

**Comment by Saipan0** [comment]
here I close the post.
If I have problems with the UE4TextExtractor program, I write on its page. not to clog here. thank you

we hope UE4LocalizationsTool gets better and better. good job for the program

**Comment by amrshaheen61** [comment]
> here I close the post. If I have problems with the UE4TextExtractor program, I write on its page. not to clog here.
> 
> we hope UE4LocalizationsTool gets better and better. good job for the program

Worked on

**Comment by Saipan0** [comment]
> Worked on

okok thanks. do I leave the post closed?

**Comment by amrshaheen61** [comment]
> hello, first of all thank you for the previous problem. Your update has been a success, It has worked wonderfully.
> 
> I have a problem with texts not being extracted / found by your program. I am attaching the files so you can see. There are texts in .uexp which are not found in the uasset file .. or in any case they are not displayed. The problem persists in multiple files, the one I am attaching is one in general.
> 
> [File.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/8913984/File.zip)
> 
> can a solution be found? thank's for your job

What is the name of this game?

**Comment by Saipan0** [comment]
> What is the name of this game?

[file.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/8987800/file.zip)

I entered the link to download it. read information
thanks
