### ISSUE TITLE
Not all lines are found in locres

### ISSUE THREAD

**Issue by ponaromixxx** [amrshaheen61/UE4LocalizationsTool#14]
Hello. The program ignores duplicate lines, but they have a different key. Is this by design or not? Or will the program replace similar lines when importing?

**Comment by TheDarkness1994** [comment]
Can you show an example?

**Comment by amrshaheen61** [comment]
@ponaromixxx 
No example so I can't help you

**Comment by amrshaheen61** [comment]
@ponaromixxx 
This line only exists once
![image](https://user-images.githubusercontent.com/65582303/176348318-c2fadfa8-a199-4599-8d50-7ddbc999398c.png)

The tool you are using is extracting all lines according to kay value
![image](https://user-images.githubusercontent.com/65582303/176348625-69aa11f2-be3f-4844-a5c1-98c6842b0e5d.png)

**Comment by ponaromixxx** [comment]
Hello, can you please add additional name detection
![изображение](https://user-images.githubusercontent.com/13481596/178121903-b8608d84-134f-42ef-b4c7-e9c17b8b61e9.png)

[Nuts.locres](https://mega.nz/file/14BVHS7K#9qyzJZG2C7WwcxXdRKihSP26Wf64om44M-inbA4xe9A)

Thanks
