### ISSUE TITLE
Export problem

### ISSUE THREAD

**Issue by Mayki07** [amrshaheen61/UE4LocalizationsTool#15]
Hey. I have a question. Would there be any way to export text only from the selected row? Using the TEXT filter I can export all the rows with text.

![UE4](https://user-images.githubusercontent.com/35667524/178101438-0622a44e-cb66-4d11-a031-f59dbc543fed.jpg)

I am also attaching a test file
[Testfile.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/9076273/Testfile.zip)
.

**Comment by amrshaheen61** [comment]
![image](https://user-images.githubusercontent.com/65582303/178105819-5a351750-1608-43d5-a728-36c93671782e.png)
@Mayki07 
this what you need?

**Comment by Mayki07** [comment]
That's exactly what I need... :+1:

**Comment by amrshaheen61** [comment]
@Mayki07 
here [v1.8](https://github.com/amrshaheen61/UE4LocalizationsTool/releases/tag/v1.8)

i think this game is little hope use commands it will make your work more easier
![image](https://user-images.githubusercontent.com/65582303/178107178-89907289-e2a2-4f60-b83a-492de5c30772.png)

close the issue if everything goes well

**Comment by Mayki07** [comment]
Awesome job again, thanks for the help.
