### ISSUE TITLE
[REQUEST] Xml Support!

### ISSUE THREAD

**Issue by Soi9x** [amrshaheen61/UE4LocalizationsTool#16]
Hello Source Coder , The Source Code Is Awesome , Can You Add XML Support Function ? , If Yes, That's Great

**Comment by amrshaheen61** [comment]
@Soi9x 
why?

**Comment by Soi9x** [comment]
> @Soi9x why?

because I need to Vietnameseize the Eldenring game language

**Comment by amrshaheen61** [comment]
@Soi9x 
right now no plan for this

**Comment by Soi9x** [comment]
> right now no plan for this

but, your tool is great if you add that functionality!
