### ISSUE TITLE
Additional lines

### ISSUE THREAD

**Issue by ponaromixxx** [amrshaheen61/UE4LocalizationsTool#17]
Hello, can you please add additional name detection

![изображение](https://user-images.githubusercontent.com/13481596/178121903-b8608d84-134f-42ef-b4c7-e9c17b8b61e9.png)

[Nuts.locres](https://mega.nz/file/14BVHS7K#9qyzJZG2C7WwcxXdRKihSP26Wf64om44M-inbA4xe9A)

Thanks

_Originally posted by @ponaromixxx in https://github.com/amrshaheen61/UE4LocalizationsTool/issues/14#issuecomment-1179603856_

**Comment by amrshaheen61** [comment]
@ponaromixxx 
here, this is what you want?
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/9077941/UE4localizationsTool.zip)

**Comment by ponaromixxx** [comment]
Yes, it extracts these lines and I redid it a little so that it extracts as it should, but I like this program more and it seems more convenient.

**Comment by TheDarkness1994** [comment]
@ponaromixxx What game is this? It became interesting.

**Comment by ponaromixxx** [comment]
> @ponaromixxx What game is this? It became interesting.

It Takes Two

**Comment by ponaromixxx** [comment]
[amrshaheen61](https://github.com/amrshaheen61), Sorry, I forgot to thank you, thank you very much for listening and helping with problems.

**Comment by amrshaheen61** [comment]
@ponaromixxx 
You are welcome
