### ISSUE TITLE
[REQUEST] Edit filter name

### ISSUE THREAD

**Issue by Mayki07** [amrshaheen61/UE4LocalizationsTool#18]
Hi, would it be possible to create a filter from only part of the name? I would like to search and export text using the filter, but instead of a long name, only part of it would be enough. For example, instead of : 

**documentnameEnglish_47_9E5E8B53476DB30D4C453AB0FD3F3828**
**documentcontentEnglish_48_EDF3F13E480D12715D33C7BFD39BEF4B** 

I would only want 

**English_47** 
**English_48**

and then that would show up in the exported text. Would such a thing be possible? 

![Test](https://user-images.githubusercontent.com/35667524/188319759-0e38f238-40de-477f-8dac-49d36f93af51.jpg)
![Test1](https://user-images.githubusercontent.com/35667524/188319769-27f5c09f-705b-4576-a39b-9f2fa7492121.jpg)

I know that it is possible to export text without a name, but this option doesn't suit me at all.
Thank you for the answer.

**Comment by amrshaheen61** [comment]
@Mayki07 
You can modify all names after export it the tool does not read the names
you can use notepad++ for this like this
![image](https://user-images.githubusercontent.com/65582303/188320862-a9c96089-6674-46c1-bf1d-4aab5314a6d5.png)
![image](https://user-images.githubusercontent.com/65582303/188320870-f2fd2854-9ed8-4c17-b782-23d2e18f94da.png)

**Comment by Mayki07** [comment]
That seems like a good idea. Will it be possible to import it back afterwards, or will the text have to be edited again?

**Comment by amrshaheen61** [comment]
@Mayki07 
as i said the tool Ignore all names
it take all text after  '='

**Comment by Mayki07** [comment]
Okay, thank you for your help.
