### ISSUE TITLE
Problem with editing text

### ISSUE THREAD

**Issue by Mayki07** [amrshaheen61/UE4LocalizationsTool#19]
Hi, I have a problem with editing text in a game, I know that the BF_Key_Rebinding_Func_Lib.uexp file contains the text shown in the picture, but the UE4 Localizations Tool cannot display this text. Would it be possible to do something about it? I am attaching a file to test. Thank you for your help.

![TalesOfTomorrow](https://user-images.githubusercontent.com/35667524/192091612-a577d293-5d35-4973-a36f-95a0302ace84.jpg)

[Test.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/9638395/Test.zip)

**Comment by amrshaheen61** [comment]
@Mayki07 
test this file 
[BF_Key_Rebinding_Func_Lib.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/9649057/BF_Key_Rebinding_Func_Lib.zip)

**Comment by Mayki07** [comment]
Great, it seems to be working.

![TalesOfTomorrow 27-09-2022 14-46-48-161](https://user-images.githubusercontent.com/35667524/192530543-092f6a0e-eb9c-4b93-ba44-4b2c103b7826.png)

**Comment by Mayki07** [comment]
I have one more request, would there be any possibility to use UE4localizationsTool to access the texts that are in the *.umap files? The text in the image is in the *.umap file and not in the *.uexp file.
I am attaching a file to test.

![text](https://user-images.githubusercontent.com/35667524/192564156-4d0e2c5c-14c5-47f4-963d-f23c8a664672.JPG)
[Localization_uexp.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/9657269/Localization_uexp.zip)

**Comment by TheDarkness1994** [comment]
If it is possible to upload the game files in the archive and on a file sharing service, then I can create a locres file to edit these files. I already tried to create from those files that you sent, I succeeded.

**Comment by amrshaheen61** [comment]
Ok

**Comment by amrshaheen61** [comment]
@Mayki07 
what about this?
[BF_Key_Rebinding_Func_Lib.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/9678778/BF_Key_Rebinding_Func_Lib.zip)

**Comment by Mayki07** [comment]
Still the same problem, the game crashes when loading.
![Error](https://user-images.githubusercontent.com/35667524/193136474-5ddfd004-3995-47f9-9704-c4696fc02f65.jpg)

**Comment by amrshaheen61** [comment]
@Mayki07 
and now?
[BF_Key_Rebinding_Func_Lib.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/9679093/BF_Key_Rebinding_Func_Lib.zip)

**Comment by Mayki07** [comment]
No. Game crashes.

**Comment by amrshaheen61** [comment]
@Mayki07 
Unfortunately I will leave this issue for some time again and will come back to find a solution to it as soon as possible
thanks for test files 🌹

**Comment by Mayki07** [comment]
OK, thanks.

**Comment by heiha10** [comment]
> OK, thanks.

change .umap to .uassets ,edit it,then change .uassets to .uamp

I have localized this game.

like this 

for /r  "Radius\IntoTheRadius\Content\ITR\Levels-Quest" %%a in (*.umap) do  ren %%a *.uasset
.\tools\UE4localizationsTool.exe  -importall   "Radius\IntoTheRadius\Content" "翻译.txt"  -f
for /r  "Radius\IntoTheRadius\Content\ITR\Levels-Quest" %%a in (*.uasset) do  ren %%a *.umap

the game work well.

**Comment by Luc2as** [comment]
> > OK, thanks.
> 
> change .umap to .uassets ,edit it,then change .uassets to .uamp
> 
> I have localized this game.
> 
> like this
> 
> for /r "Radius\IntoTheRadius\Content\ITR\Levels-Quest" %%a in (*.umap) do ren %%a _.uasset .\tools\UE4localizationsTool.exe -importall "Radius\IntoTheRadius\Content" "翻译.txt" -f for /r "Radius\IntoTheRadius\Content\ITR\Levels-Quest" %%a in (_.uasset) do ren %%a *.umap
> 
> the game work well.
> 
> ![网页捕获_20-10-2022_1501_www bilibili com](https://user-images.githubusercontent.com/15613084/196878620-5d009054-77e5-4e19-8980-98f984ea722b.jpeg)

Hi, do you have this game localized ?
I'm trying to. The previous question from Mayki was more for me and just forwarded me the answers. I'm having the problem that UE4LocalizationsTool doesn't always load all the text for me. Figure 1 - Left. How did you solve this? Did you edit the hex ? Is there a lot of such texts ?

![image](https://user-images.githubusercontent.com/114860916/199701822-219fa4e1-9276-4be5-8f5a-9779d2886ce5.png)

**Comment by amrshaheen61** [comment]
@Luc2as 
Send this example

**Comment by Luc2as** [comment]
OK, sorry I have better example here.

![no_text](https://user-images.githubusercontent.com/114860916/199778714-8a928f6f-e14d-4c88-b679-84137a773b25.png)
[notext.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/9931185/notext.zip)

**Comment by amrshaheen61** [comment]
@Luc2as 
worked!
![image](https://user-images.githubusercontent.com/65582303/199813324-cb9cf011-303e-4ea7-84e8-b8cfceba76a0.png)

**Comment by Luc2as** [comment]
If I change any item in the black cells the game crashes...

![image](https://user-images.githubusercontent.com/114860916/199820492-e8563569-0867-4960-b6f0-91b81131961b.png)

**Comment by amrshaheen61** [comment]
@Luc2as 
yes i know this the reason i put this notice
![image](https://user-images.githubusercontent.com/65582303/199820862-7e8971f9-dae3-4d13-be86-6544ff6c69d5.png)

**Comment by Luc2as** [comment]
So, this text is not editable.....

**Comment by amrshaheen61** [comment]
@Luc2as 
If it's the same length, it will work
for example:
```
1. System: Game Menu<cf>2.  >>> 1. System: gggg Menu<cf>2. 
```

**Comment by Luc2as** [comment]
Okay, I understand... Thank you very much! Good work with this SW

**Comment by heiha10** [comment]
> Okay, I understand... Thank you very much! Good work with this SW

I edit a picture replaced it。like this
![image](https://user-images.githubusercontent.com/15613084/199869820-fd75966a-d3ca-46da-91c3-a2652cfb7ef3.png)

and change the position  WBP_Block_ControlsLayout.uasset

![image](https://user-images.githubusercontent.com/15613084/199870406-a8621236-2d0d-4049-bfe1-9d4c57d2a376.png)

**Comment by Luc2as** [comment]
> > Okay, I understand... Thank you very much! Good work with this SW
> 
> I edit a picture replaced it。like this ![image](https://user-images.githubusercontent.com/15613084/199869820-fd75966a-d3ca-46da-91c3-a2652cfb7ef3.png)
> 
> and change the position WBP_Block_ControlsLayout.uasset
> 
> ![image](https://user-images.githubusercontent.com/15613084/199870406-a8621236-2d0d-4049-bfe1-9d4c57d2a376.png)

Hey, man.

Thank you so much!!! Thank you so much!!! Can I ask you about any other problems that I have discovered or I will discover ? In a private message ? Email ?

**Comment by heiha10** [comment]
> > > Okay, I understand... Thank you very much! Good work with this SW
> > 
> > 
> > I edit a picture replaced it。like this ![image](https://user-images.githubusercontent.com/15613084/199869820-fd75966a-d3ca-46da-91c3-a2652cfb7ef3.png)
> > and change the position WBP_Block_ControlsLayout.uasset
> > ![image](https://user-images.githubusercontent.com/15613084/199870406-a8621236-2d0d-4049-bfe1-9d4c57d2a376.png)
> 
> Hey, man.
> 
> Thank you so much!!! Thank you so much!!! Can I ask you about any other problems that I have discovered or I will discover ? In a private message ? Email ?

Yeah，if I can.

**Comment by Luc2as** [comment]
Thanks for any help ! But I don't want to interact here and spam this thread with specific questions. Any idea for private communication. I will be very grateful for your advice. Email is not visible on github.

**Comment by heiha10** [comment]
> 

heiha10@sina.cn  &  634833476@qq.com

**Comment by heiha10** [comment]
> 感谢您的任何帮助！但我不想在这里互动并用特定问题向该线程发送垃圾邮件。任何私人交流的想法。我将非常感谢您的建议。电子邮件在 github 上不可见.

heiha10@sina.cn& 634833476@qq.com

**Comment by Luc2as** [comment]
Thanks!

**Comment by Luc2as** [comment]
> @Luc2as If it's the same length, it will work for example:
> 
> ```
> 1. System: Game Menu<cf>2.  >>> 1. System: gggg Menu<cf>2. 
> ```

Hey, man.
I have an idea, would it be possible to make a checkbox in the menu that would prevent editing more characters than the black cell contains?
I'm constantly counting them, editing them and the game crashes often.

**Comment by amrshaheen61** [comment]
@Luc2as 
![image](https://user-images.githubusercontent.com/65582303/200291037-d9b91cf6-954c-4c49-9871-8f8fddf53e54.png)
![image](https://user-images.githubusercontent.com/65582303/200291053-4daed93b-649e-4316-9858-a7d5a3af6dd3.png)

[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/9950654/UE4localizationsTool.zip)

**Comment by Luc2as** [comment]
> @Luc2as ![image](https://user-images.githubusercontent.com/65582303/200291037-d9b91cf6-954c-4c49-9871-8f8fddf53e54.png) ![image](https://user-images.githubusercontent.com/65582303/200291053-4daed93b-649e-4316-9858-a7d5a3af6dd3.png)
> 
> [UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/9950654/UE4localizationsTool.zip)

Hi, 
thank you so much! You're the first person to ever edit something on Github for me !!!

Thank you again!

**Comment by Luc2as** [comment]
And small bug here.


https://user-images.githubusercontent.com/114860916/200375343-6a166572-476c-4a00-b7d3-6eb30cecf21b.mp4

**Comment by amrshaheen61** [comment]
@Luc2as 
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/9954099/UE4localizationsTool.zip)
It won't effect but here it is, btw did you test the game after modify the file?

**Comment by Luc2as** [comment]
I know it's just aesthetics. I work with it all the time, yes game tested. Mostly it notifies me when the game crashes. How many times is the text long there are spaces etc.

**Comment by Luc2as** [comment]
> > 感谢您的任何帮助！但我不想在这里互动并用特定问题向该线程发送垃圾邮件。任何私人交流的想法。我将非常感谢您的建议。电子邮件在 github 上不可见.
> 
> [heiha10@sina.cn](mailto:heiha10@sina.cn)& [634833476@qq.com](mailto:634833476@qq.com)

Hey, man,
I sent you an e-mail about the menu texts.
Is there a solution? Can it be localized?

Thanks for the reply

**Comment by heiha10** [comment]
> Hey, man, I sent you an e-mail about the menu texts. Is there a solution? Can it be localized?
> 
> Thanks for the reply

Didn't you get the email? If you mean "custom", "Highly Decreased", "For Player and Enemies", etc.Yes ,they could. I have sent an email. Contains a "file. zip"

**Comment by Mayki07** [comment]
Hi, I'm having trouble editing text again. I need to edit (translate) text, but it is in a uexp file , not in uasset. Is there anything I can do about it?

![SS](https://github.com/amrshaheen61/UE4LocalizationsTool/assets/35667524/b9389243-14d0-48df-869d-8edf107ae91e)

I am attaching a file to test.
[TestFile.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11629803/TestFile.zip)

**Comment by amrshaheen61** [comment]
@Mayki07
![image](https://github.com/amrshaheen61/UE4LocalizationsTool/assets/65582303/e5d186d0-0d2b-49d1-af36-0a3648da1c27)
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11641781/UE4localizationsTool.zip)

**Comment by Mayki07** [comment]
OK, thanks...

**Comment by Mayki07** [comment]
Hi, I have another problem with text editing. I only have a uasset file that contains text. I am unable to open the file in your tool. Is there any way to edit the text?
I am attaching a test file.

![Test](https://github.com/amrshaheen61/UE4LocalizationsTool/assets/35667524/3b9bf1d2-324c-4be8-9cd2-b03950926801)

[Test_file.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11778409/Test_file.zip)

**Comment by amrshaheen61** [comment]
@Mayki07 
test this
![image](https://github.com/amrshaheen61/UE4LocalizationsTool/assets/65582303/d249999e-56e5-4734-9d92-ac718acf080b)
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11779733/UE4localizationsTool.zip)

**Comment by Mayki07** [comment]
I don't know what I'm doing wrong, but no text has shown up.

![Test1](https://github.com/amrshaheen61/UE4LocalizationsTool/assets/35667524/0f007eed-3578-4523-b880-686a19533c67)

**Comment by Mayki07** [comment]
Hi, I have some uasset text file here, but I can't open it in your program. Would you take a look at it, please? I'm attaching a test file.
[Test_file.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/12446632/Test_file.zip)

**Comment by amrshaheen61** [comment]
@Mayki07 
https://github.com/amrshaheen61/UE4LocalizationsTool/releases/tag/v2.3

**Comment by Mayki07** [comment]
Beautiful work, thank you...
