### ISSUE TITLE
Problem with loading files

### ISSUE THREAD

**Issue by AliGMods** [amrshaheen61/UE4LocalizationsTool#20]
Hello I have a problem with loading this file in UE4LocalozationTool1.9. Would it please be possible to solve this problem.
Not all texts will be displayed.
Thank you I am attaching the files for testing.
[Maine.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/9690530/Maine.zip)

**Comment by amrshaheen61** [comment]
@AliGMods 
Like what?

**Comment by AliGMods** [comment]
If I want to load the files, they don't load in their entirety. It says This file is not fully parsed and may not contain some text. The file does not load completely and is missing text.

**Comment by amrshaheen61** [comment]
@AliGMods 
here test it 
close issue if your problem is solved
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/9691385/UE4localizationsTool.zip)

**Comment by AliGMods** [comment]
It's working, thank you very much.
