### ISSUE TITLE
cmd can't export umap

### ISSUE THREAD

**Issue by heiha10** [amrshaheen61/UE4LocalizationsTool#22]
cmd can't batch export umap，only can export uasset &locres. I wish this function can be added. Thanks a lot.

**Comment by amrshaheen61** [comment]
@heiha10 
here [v2.0](https://github.com/amrshaheen61/UE4LocalizationsTool/releases/tag/v2.0)

**Comment by heiha10** [comment]
> @heiha10 here [v2.0](https://github.com/amrshaheen61/UE4LocalizationsTool/releases/tag/v2.0)

Great work！ Thanks so much。
