### ISSUE TITLE
In version 2.0 console commands do not work

### ISSUE THREAD

**Issue by KASaLEX-2020** [amrshaheen61/UE4LocalizationsTool#23]
In version 2.0 console commands do not work -f and -nn. In version 1.9 everything works

**Comment by amrshaheen61** [comment]
@KASaLEX-2020 
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/10025016/UE4localizationsTool.zip)

**Comment by KASaLEX-2020** [comment]
It all works now. THANK YOU.
