### ISSUE TITLE
An issue with text edit

### ISSUE THREAD

**Issue by Moder5ly** [amrshaheen61/UE4LocalizationsTool#24]
Hello! I'm currently working on a localization of Like a Dragon: Ishin! and while the tool works perfectly with most of the lines, it still doesn't work at all with some. 

With some investigation I came to a conclusion that the game cannot see the changed strings if the key of that string doesn't have any directories specified before it. Check the examples in the screenshot and below. 

For instance, we have two lines in the .locres file:

key                               |     text value
------------------------+-----------------
**something/**something | something           > it gets translated it has a directory "something/" before the actual name of string
anything                      | anything               > nothing changes

Is there a workaround to this issue? I've attached the .locres file just in case you need it.

P.S.: I also used method 2, it didn't help.

![Без імені](https://user-images.githubusercontent.com/22967222/222016607-dd6ead19-0a39-4f78-92cf-2b1f993b2ad6.png)

[Game.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/10856004/Game.zip)

**Comment by Moder5ly** [comment]
I have to add here, that the string which doesn't work should have a key "category/game;name" (checked with a different tool which also doesn't seem to work), but it seems that the directory (category/ in this case) gets trimmed by the tool or something, and I think that this causes the issue.

The string which works either way should also have a prior directory shown. The full key of that string is "surfboard/TitleMenu/Menu/01", but in the tool only "TitleMenu/Menu/01" is shown.

**Comment by amrshaheen61** [comment]
check them in any other language file in game

**Comment by Moder5ly** [comment]
Yes, I checked other files, but they didn't get changed either. I think that the issue is not with the .locres but with other file. We'll try fixing the issue there. You may consider this case closed. By the way, what HEX editor you are using?
