### ISSUE TITLE
Error Not enought data

### ISSUE THREAD

**Issue by isme99** [amrshaheen61/UE4LocalizationsTool#25]
Game name: blue protocol
Unreal Engine ：4.27.2 
Error Not enought data
![111](https://user-images.githubusercontent.com/56696567/222068993-9a2c53cd-ae7c-4257-a4f4-eb38088a8f22.png)
Game file
[Text.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/10858062/Text.zip)
Thank you for your efforts!

**Comment by amrshaheen61** [comment]
@isme99 
all files is empty
try another tool to export them again

![Screenshot 2023-03-02 214610](https://user-images.githubusercontent.com/65582303/222536316-d4f7f1f3-a101-4d02-ac5a-1805d69f9430.png)
