### ISSUE TITLE
Can't insert line breaks / new lines

### ISSUE THREAD

**Issue by pepperonzo** [amrshaheen61/UE4LocalizationsTool#26]
Hello,
First of all: thank you for your tool, it's very useful.
I'm currently using your UE4LocalizationsTool 2.1 version to translate a game.
The game has lots of wrapped text inside dialogue boxes
When I edit these lines, then save the .locres and pack it, the game ignores formatted text, showing the "code"
Here's an example:

This is the line inside UE4LocalizationsTool:
`Journal:<lf><lf>Today's board meeting could be interesting. I look forward to finally making a move on the acquisition. They're ripe for the taking.`

If left unedited it shows like this in game (as it should):
```
Journal:

Today's board meeting could be interesting. I look forward to finally making a move on the acquisition. They're ripe for the taking.
```

But as soon as I translate the line, the game shows:
`Journal:<lf><lf>Today's board meeting could be interesting. I look forward to finally making a move on the acquisition. They're ripe for the taking.`

showing `<lf>`. the same happens with other formatting symbols like `<q></>` and `<k></>`

I already tried adding `\r\n, \n, <br>` to wrap text but they just show in game as they are

Thank you for your help

**Comment by amrshaheen61** [comment]
@pepperonzo 
i'm sorry about that, download it again and try it
[v2.1](https://github.com/amrshaheen61/UE4LocalizationsTool/releases/tag/v2.1)

**Comment by pepperonzo** [comment]
Wonderful, it worked!
now <lf> wraps text correctly. Thank you so much for your quick response!
