### ISSUE TITLE
Problem saving file

### ISSUE THREAD

**Issue by eduaratol** [amrshaheen61/UE4LocalizationsTool#27]
Hello, first of all I would like to thank you for developing this tool that has been very useful for me to translate a game into my native language.

With it, I have already been able to translate a large part of the game, but at the moment I am unable to save one of the files.

I can do everything, open, export, import... But when it comes to saving, the file seems to corrupt and lose all data. As a test, I will send this file as an attachment. Please try to open, save, and then open the saved file.

Thank you in advance for providing the tool.

[Files.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11071027/Files.zip)

**Comment by amrshaheen61** [comment]
@eduaratol 
test this
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11071680/UE4localizationsTool.zip)

**Comment by eduaratol** [comment]
@amrshaheen61 
It worked! Now I can save, but inside the game the texts are getting confused as if they are part of other references, but I believe this is related to another problem now, I will try to investigate what it might be.

Thank you very much for your help!
