### ISSUE TITLE
Fatal error when modifying file *.uasset

### ISSUE THREAD

**Issue by brtraducoes** [amrshaheen61/UE4LocalizationsTool#28]
I am translating these files, if I change in hexadecimal works normal, but if I use your tools crach the game if you can help me I thank you.

Example of some files
https://drive.google.com/file/d/1LAdjohi6bkoGd29KcjtYpgrhmyme8-zH/view?usp=share_link

Text to translate Press {X} to crouch!

**Comment by amrshaheen61** [comment]
@brtraducoes 
can't edit function
you can find more information here
https://github.com/amrshaheen61/UE4LocalizationsTool/issues/19

**Comment by brtraducoes** [comment]
Thanks!
