### ISSUE TITLE
No text from uexp

### ISSUE THREAD

**Issue by Luc2as** [amrshaheen61/UE4LocalizationsTool#29]
Hi
I have a case where the tool won't pull text from a uexp file. 
I can see it through the hex editor. If I use UE4TextExtractor.exe on these files which creates a new locres file it also extracts it. It is for example the text "No pleasantries." Hey." etc...

File attached.

Thanks for the response

Lucas
[Visit1.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11133153/Visit1.zip)

**Comment by amrshaheen61** [comment]
@Luc2as 
![image](https://user-images.githubusercontent.com/65582303/229378731-4987591d-5b93-4f8e-9df2-6e781cc42f70.png)
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11133346/UE4localizationsTool.zip)
close this issue if it work

**Comment by Luc2as** [comment]
Thanks, work perfect !!
