### ISSUE TITLE
Array dimensions exceeded supported range.

### ISSUE THREAD

**Issue by MalachiMassey** [amrshaheen61/UE4LocalizationsTool#3]
I got this popup error: "Array dimensions exceeded supported range." while trying to open a Chinese game file. Is there a patch or work-around for this?

**Comment by amrshaheen61** [comment]
@MalachiMassey 
can you send it?

**Comment by MalachiMassey** [comment]
I got the same error with version v1.1.
Here's the file:
https://drive.google.com/file/d/1KV7H8oDmpiSydze7r5fUTfZJ_j29F7l1/view?usp=sharing

**Comment by amrshaheen61** [comment]
This file is corrupt try to extract it again with [fmodel](https://github.com/iAmAsval/FModel)
