### ISSUE TITLE
How to convert uexp files to uasset？

### ISSUE THREAD

**Issue by notcookies** [amrshaheen61/UE4LocalizationsTool#30]
Hi,
I am trying to export the text directly from inside the uexp file. The UE4localization tool supports only files of uasset. I have browsed many of your replies on closed issue, and the attached uasset file with the same name is in your reply. How do I convert a uexp file to a uasset file?

**Comment by amrshaheen61** [comment]
@notcookies 
Hello sir, uexp must have uasset file
If not send it

**Comment by notcookies** [comment]
How can I convert any *.uexp file into a *.uasset file and then use UE4localization Tool to modify the text?

**Comment by amrshaheen61** [comment]
@notcookies 
Unfortunately I don't know
