### ISSUE TITLE
Can't parse this game localize

### ISSUE THREAD

**Issue by AyraHikari** [amrshaheen61/UE4LocalizationsTool#32]
The tools can't parse this game localize, it have warning: this file isn't fully parsed.
And not parse any text inside. However, when opens with hex, it has some tables.

### Screenshot
![image](https://user-images.githubusercontent.com/36266025/235952395-a6671cc8-223e-4141-a121-d8713f33cdcd.png)

## Files

- [SystemText.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11383859/SystemText.zip)

![image](https://user-images.githubusercontent.com/36266025/235955797-6381106e-6bf7-43fa-a71c-4cbbce36b7a4.png)

**Comment by amrshaheen61** [comment]
@AyraHikari 
What is the name of this game?

**Comment by AyraHikari** [comment]
Octopath Traveler: Champions of the Continent

**Comment by amrshaheen61** [comment]
test this, if everything goes right, close this issue.
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11399499/UE4localizationsTool.zip)

**Comment by AyraHikari** [comment]
All SystemText is parsed fine, however TalkText still can't be parsed (sorry i forgot to provide it)
[TalkText.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11405257/TalkText.zip)

**Comment by amrshaheen61** [comment]
@AyraHikari 
what about now?
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11406104/UE4localizationsTool.zip)

**Comment by AyraHikari** [comment]
Working fine now, thank you very much.
