### ISSUE TITLE
DNDThis value '-5036' is non number and out of range

### ISSUE THREAD

**Issue by 912061442** [amrshaheen61/UE4LocalizationsTool#33]
/![image](https://user-images.githubusercontent.com/47880466/236752770-271ebcba-dc7e-4e3b-8877-4c08a6d18a55.png)

**Comment by amrshaheen61** [comment]
@912061442 
Where is the example?

**Comment by 912061442** [comment]
https://github.com/912061442/123

**Comment by 912061442** [comment]
@amrshaheen61 https://github.com/912061442/123
Actually, this error is a positive number in the code, and when it reaches the value, it is a negative number

**Comment by 912061442** [comment]
@amrshaheen61 Thanks
