### ISSUE TITLE
uasset file missing a line of text

### ISSUE THREAD

**Issue by enarkay** [amrshaheen61/UE4LocalizationsTool#36]
[cinematic.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11832690/cinematic.zip)
I've attached a zip file containing the set of both uasset and uexp files called 'cinematic'

While my search results and understanding is that when loaded with the tool, the uasset should display the two following lines of text :
1) October 11, my wife and my son and I were in the house but my wife went to the kitchen and then I heard a loud scream
2) when I went I saw her head cut off and I saw a tall man without a mouth coming out of the window and I left the house

I am only able to see the first line of text, and the second line of text is missing / not displaying. I've noticed that the top bar of the program displays "This file isn't fully parsed and may not contain some text" when loading the uasset file, so maybe it's a parsing error.

Could you take a look into it? Thank you very much in advance!

**Comment by amrshaheen61** [comment]
download this
https://github.com/amrshaheen61/UE4LocalizationsTool/issues/19#issuecomment-1595823566

**Comment by enarkay** [comment]
Thank you very much, it solved the problem :) Are all these changes coming to an update in a future release?

**Comment by enarkay** [comment]
@amrshaheen61 I've actually realized that launching the game after fixing the text crashes the game.
![image](https://github.com/amrshaheen61/UE4LocalizationsTool/assets/7910166/83a335ac-0bcb-4e77-9da4-532da7b4f098)

I will do some more experiments on my end and provide you with whatever (crash) logs I can get if possible, but if you have something you could try on your end then please let me know. Thank you.

**Comment by amrshaheen61** [comment]
@enarkay 
test this
[cimatic.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11839627/cimatic.zip)

**Comment by enarkay** [comment]
Yup still the same thing - in my previous patch or with the patch I just tried by editing your attachment, the game crashes once I press play. Here is the attachment with the new crash logs, as well as your attachment with text edits
[crashlog.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11839918/crashlog.zip)

**Comment by amrshaheen61** [comment]
@enarkay 
ok, thanks.

**Comment by enarkay** [comment]
@amrshaheen61 Okay but thank you very much anyways for giving it a try!
