### ISSUE TITLE
[Feature Request] A csv/tsv export/import feature

### ISSUE THREAD

**Issue by enarkay** [amrshaheen61/UE4LocalizationsTool#37]
It's not something I need really desperately but if it isn't too hard or would bother yout too much to implement,
I would very much like to request a feature to export or import locres files in a csv/tsv format.

As someone who makes fan localization game patches on a rather regualy basis,
I have a lot of translation and game files accumulated for all sorts of different games so far.

In order to both make my translation work process efficient and keep things organized for easier maintenance in case of updates,
I prefer to upload and maintain my translations on google drive, in particular google sheets.

In this sense, the format of string tables I prefer the most is a csv/tsv with three columns, where each columns are :
Key(name)	Source(original text)	Target(translated text)

While it is still technically possible to do this with the curret txt format of your tool where the export/import format is "name=value",
it does require a bit of manual labor to convert this format to a sheet material and vice versa.

Although there is another tool that exactly does this (UnrealLocres),
I would very much like to be able to resort to just one tool for everything, instead of having to rely on multiple tools for the job.

**Comment by amrshaheen61** [comment]
@enarkay 
test this
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11952809/UE4localizationsTool.zip)

**Comment by enarkay** [comment]
Wow that was incredibly fast! Thank you so much :)
So I've tested the export to csv feature to see what kind of format it uses/produces.
And after seeing the results, I would like to ask for two changes to the format :

**1)** Add an extra 3rd column for translation
**2)** Add a header row on top as the first row (ex. Key, Source, Target)

An example with the above changes implemented would be something like below :

**<When exporting>**
Key, Source, Target
Key1, OriginalText1, (empty)
Key2, OriginalText2, (empty)

**<When importing>**
Key, Source, Target
Key1, OriginalText1, TranslatedText1
Key1, OriginalText2, TranslatedText2


I suggested the two above changes NOT just based on my personal work style, but based on the average standard format I've seen across localization platforms/services.

For example, a popular translation service, Crowdin, just won't accept files unless it has AT LEAST the three columns of Key, Source, Target.

So the current exported csv format from the tool, which only has two columns, simply cannot be imported at all in Crowdin.

Unless the translation platform/service is particularly flexible, other translation platforms/services are pretty similar to Crowdin, if my memory serves me correctly.

**Comment by amrshaheen61** [comment]
hope this what you need
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11972767/UE4localizationsTool.zip)
make sure "Translation" column is not empty
![image](https://github.com/amrshaheen61/UE4LocalizationsTool/assets/65582303/b0032b72-c3f5-4578-9943-a3d761bb8683)

**Comment by enarkay** [comment]
Thanks for the update.

I have both a question and perhaps a request.

**Question)** Will the program have no trouble importing csv files, if the double quotes(") at each ends of a column are gone?

**Request)** If not, which I'm guessing is most likely the case, would it be too much trouble / difficulty  to ask you to remove the double quotes(") at each ends of a column both when exporting and importing a csv file?

Here's an elaboration of my problem for your better understanding. I've attached three csv files in the zip file for you to take a look at :
**1) Game.locres.csv** ☞ the originally created csv from your tool
**2) Game.locres(crowdin).csv** ☞ downloaded from crowdin
**3) Game.locres(google sheets).csv** ☞ downloaded from google sheets

If you look at csv 2 (crowdin), you'll see that the crowdin effectively retains the double quotes(") at each end of each column. This is good.

However, if you look at csv 3 (google sheets), the double quotes are missing at each ends of a column. My understanding is that Microsoft-Excel-like programs/services have an inherent feature to rid the double quotes(?) at each ends of a column.

If the csv file to import requires the same format in terms of retaining double quotes(") at each ends of a column, and it is too troublesome/difficult for you to update the csv export/import feature to work with formats that do not have double quotes(") at each ends of a column, that's totally understandable.

I am grateful to you even up to this point, and I guess I can try coming up with simple functions/ways to add double quotes(") at each ends of a column to csv files download from google sheets.
[Game.locres.csv.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11973158/Game.locres.csv.zip)

**Comment by amrshaheen61** [comment]
find something wrong after send it, no need to add sting inside double quotes

test it
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/11973230/UE4localizationsTool.zip)

**Comment by enarkay** [comment]
Tested it out and it works exactly as expected. You're just a god-send, thanks so much for the wonderful implementation! I'm sorry to bother you so much but I still have some questions - but since they're unrelated to this issue, I'll close this one and open up a new one for the sake of clear distinguishment. Again, thanks a lot! :)
