### ISSUE TITLE
How to translate the Options/Language string itself in a UE4 game?

### ISSUE THREAD

**Issue by Hexaae** [amrshaheen61/UE4LocalizationsTool#38]
Sorry, maybe it's not exactly the right place, but I need help as I really can't find anything on the net about this topic: how can I change the displayed language strings in the Options of a UE4 game (I mean the language string itself: "English, Deutsch, Español...")?
For example in this game I need to translate "English" to "Italiano" since we translated the whole game, and just that language string is left... Must admit I know how to hack Unity much better than UE and I can't really figure out what kind of files should I typically search for in UE to accomplish this...

![F-I-S-T-Forged-In-Shadow-Torch-Screenshot-2023-07-01-01-35-06-41](https://github.com/amrshaheen61/UE4LocalizationsTool/assets/8591462/9265af9a-b28e-46d8-8155-431f75e18ffa)

**Comment by enarkay** [comment]
If you can't find a string in the localization folder, chances are it's in some other files like uasset or umap. In such cases, what I like to do is unpack the whole thing, search for the string I'm looking for with the tool 'Everything', then open the found result file with UE4LocalizationsTool to edit that string.

**Comment by Hexaae** [comment]
What should be the typical "localization folder" in a UE4 game?
Yes, I do the same using GrepWin... I use also Everything, but does it search also INTO files???

**Comment by enarkay** [comment]
A typical localization folder would contain one or more locres files, or may also have additional leftover files such as archive files or po files. Not sure about GrepWin but Everything can search inside files as well. That's usually how I find any strings missing from locres files in other uasset or umap files.

![image](https://github.com/amrshaheen61/UE4LocalizationsTool/assets/7910166/870ab247-4560-473a-b692-f14926376f2b)

**Comment by Hexaae** [comment]
Uh, all this time and I never noticed Advanced search panel with search in file options... 😮 thanks!
Tried with locres but found nothing related to language string itself...

**Comment by enarkay** [comment]
First of all, file list means nothing at this point. There's nothing anyone can do to help you with just a list.

Second, I was going to say maybe ask this sort of questions completely unrelated to the tool/project on a more general site such as xentax, but it seems like you've already created a post with the same question there, so why ask here?

**Comment by Hexaae** [comment]
Well, it actually helped a lot... after a re-analysis (right after I posted the link) by the name/structure of files and dirs I was able to guess where are they actually stored: the game in the end uses a big texture with all language names and crops from there the single texture strings in the first message screenshot (English, Deustch etc.):

 `
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage.uasset
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage.uexp
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Han.uasset
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Han.uexp
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_0.uasset
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_0.uexp
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_1.uasset
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_1.uexp
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_2.uasset
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_2.uexp
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_3.uasset
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_3.uexp
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_4.uasset
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_4.uexp
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_5.uasset
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_5.uexp
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_6.uasset
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_6.uexp
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_7.uasset
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_7.uexp
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_8.uasset
ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage_Sprite_Language_8.uexp
`
Yes, I wasn't sure about posting here but as a language localization tool was the closest place maybe... ;)
Now I'll see what I can do with those files to be able to edit the texture "ZingangGame\Content\UI\Common\LanguageTexture\T_UI_SelectLanguage.uexp" and modify that directly English -> Italiano.
Unfortunately UAE4LocalizationsTool as far as I can understand won't help in this case since it's a texture and not a text string.
Thanks for your time anyway... 🙏🏻

**Comment by Hexaae** [comment]
I'll close this thread as it became off-topic since textures are involved in this case...
