### ISSUE TITLE
Postal 4

### ISSUE THREAD

**Issue by gunhandroid** [amrshaheen61/UE4LocalizationsTool#4]
hi my friend;

your tool is amazing thanks. but in postal 4, game subtitles are in uexp file. how can we export it?

**Comment by amrshaheen61** [comment]
@gunhandroid 
Could you please send example?!

**Comment by gunhandroid** [comment]
[https://cdn.discordapp.com/attachments/900453858256486401/980049429149126666/BP_RWSSubtitlesSystem.rar](url)
this is the subtitles .uasset and .uexp files for postal 4.

**Comment by amrshaheen61** [comment]
@gunhandroid 
Fixed, [v1.3](https://github.com/amrshaheen61/UE4LocalizationsTool/releases/tag/v1.3)

**Comment by gunhandroid** [comment]
> @gunhandroid Fixed, [v1.3](https://github.com/amrshaheen61/UE4LocalizationsTool/releases/tag/v1.3)

brilliant... thanks

**Comment by TheDarkness1994** [comment]
> > @gunhandroid Fixed, [v1.3](https://github.com/amrshaheen61/UE4LocalizationsTool/releases/tag/v1.3)
> 
> brilliant... thanks

I think you can close the issue
