### ISSUE TITLE
Export many files with method 2 ?

### ISSUE THREAD

**Issue by Saipan0** [amrshaheen61/UE4LocalizationsTool#40]
Hello, congratulations again for your work. is it possible to export many files using method 2?

UE4localizationsTool.exe exportall Actions text.txt -method2

I tried to do it this way, but it doesn't work. can it be implemented?

I attached some files where the lyrics are present

[File](https://workupload.com/file/TjRtmFwzNYy)

Thank you!

**Comment by amrshaheen61** [comment]
@Saipan0 

UE4localizationsTool.exe exportall "FOLDER PATH" text.txt -method2

**Comment by amrshaheen61** [comment]
@Saipan0 
test this
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/12255727/UE4localizationsTool.zip)

**Comment by Saipan0** [comment]
> @Saipan0 test this [UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/12255727/UE4localizationsTool.zip)

![Immagine](https://github.com/amrshaheen61/UE4LocalizationsTool/assets/101728572/03661715-17a6-4d8b-89f5-b8022577395a)

It works perfectly, it extracts everything. Thanks you :)
Only some files take a while to read
I've marked them in red and I'm attaching them if you need them for checking.

[File3](https://workupload.com/file/gvFxSs7JvpM)

Due to these files taking a long time to read, the process with method 2 takes a long time before it finishes all the files

**Comment by amrshaheen61** [comment]
@Saipan0 

this files not contain any text

**Comment by Saipan0** [comment]
ok thanks, just one question and then we can close the post.

In addition to extracting and importing, do you also have a function just to read the file in the The command prompt (cmd)?
For example like this:

UE4localizationsTool.exe **read** Actions.uasset

**Comment by amrshaheen61** [comment]
@Saipan0 
read or export?

**Comment by Saipan0** [comment]
if it were possible to view the contents in the cmd without having to extract it. but I solved what I wanted to do.
thanks
