### ISSUE TITLE
SubtitlesText.uasset

### ISSUE THREAD

**Issue by MuratGundo** [amrshaheen61/UE4LocalizationsTool#41]
I can't open the file only SubtitlesText.uasset what should I do

**Comment by MuratGundo** [comment]
](url)[https://www.mediafire.com/file/iadc4d7ng2892no/SubtitlesText.uasset/file[](url)

**Comment by amrshaheen61** [comment]
@MuratGundo 
https://github.com/amrshaheen61/UE4LocalizationsTool/releases/tag/v2.3

**Comment by ob2code** [comment]
@amrshaheen61 help me find out how to open this file (Little Hope - Switch version), v2.3 doesn't work!

 https://www.mediafire.com/file/qcio2yzocjphl8b/buscrash_diversion.uasset/file

Thank you very much.
