### ISSUE TITLE
Add new lines in .locres file

### ISSUE THREAD

**Issue by LiaNdrY** [amrshaheen61/UE4LocalizationsTool#42]
Please make it possible to add new lines to the locres file. This is necessary to add text that is used in the game, but is not in the .locres file.

**Comment by enarkay** [comment]
I believe putting in '<cf>' allows you to change lines.

**Comment by LiaNdrY** [comment]
> I believe putting in '' allows you to change lines.

By new line I mean new value **namespace::key=value**

**Comment by amrshaheen61** [comment]
@LiaNdrY 
test test
https://github.com/amrshaheen61/UE4LocalizationsTool/files/12683570/UE4localizationsTool.zip

**Comment by LiaNdrY** [comment]
> @LiaNdrY test test https://github.com/amrshaheen61/UE4LocalizationsTool/files/12683570/UE4localizationsTool.zip

Sorry for my English:
Unfortunately, I can’t fully test it at the moment, but I can already see the error. If you do not fill in the **NameSpace**, then the :: is not placed in front of the key.

And as far as I know, the hash that is used must match the main language file. For example, you are translating a game into Spanish. You take a file with Spanish localization and try to add new lines to it. But the hash should not be calculated in the Spanish localization file, but in the main localization file (usually English localization) and transferred to the Spanish localization file, otherwise the game will not see new lines.

**Comment by amrshaheen61** [comment]
@LiaNdrY 
Add new line from (locres operation> add new row)

Namespace::stringkey, text value

The tool calculate the new keys and namespaces

**Comment by LiaNdrY** [comment]
@amrshaheen61
Ok, I'll be able to test in about 5 hours.

**Comment by LiaNdrY** [comment]
@amrshaheen61
Export after sorting does not work yet. And make it possible to export after sorting so that it saves the sorting to the exported file. Otherwise, it's useless.

**Comment by LiaNdrY** [comment]
@amrshaheen61
I tested, as I said, there was an error in the separator ::
The game is currently launching without support for the selected language.

**Namespace::stringkey=text value**

If we separate these variables, it now looks like this:

**Namespace::**
**stringkey**
**text value**

And it should be like this:

**Namespace**
**::stringkey**
**text value**

The delimiter sign **/** aka **::** an integral part of the variable - **stringkey**

Also, if you sort by the **namespace::keystring** field and then try to export, the program crashes with an error (only export to CSV works).

**Comment by amrshaheen61** [comment]
@LiaNdrY 
Send the example file to test

**Comment by LiaNdrY** [comment]
@amrshaheen61
https://drive.google.com/file/d/1aWqy40q6ArFUQYPOXnT2whv4fhJJKjzL/view

I have generated 2 files, they are fully working.

**Comment by amrshaheen61** [comment]
@LiaNdrY 

Add new Lines work fine 
about delimiter, :: not a part of file
![image](https://github.com/amrshaheen61/UE4LocalizationsTool/assets/65582303/28573895-7b8a-4af5-98b4-ae52322ee72b)

about sorting here
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/12690995/UE4localizationsTool.zip)


if you add new file call for example "aa" this will not add it as a lang ingame

**Comment by LiaNdrY** [comment]
@amrshaheen61

Does not work. I just did a simple test. I took the full **Game.locres** file, opened it in the program and immediately saved it without making any changes. I took the resulting file and threw it into the game. The game does not see it and loads English by default.

If you simply compare two binary files, the source and the saved one, you will immediately see a bunch of changes, but there shouldn’t be any.

**Comment by amrshaheen61** [comment]
@LiaNdrY 
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/12692051/UE4localizationsTool.zip)
![image](https://github.com/amrshaheen61/UE4LocalizationsTool/assets/65582303/a543c599-65bb-49fd-b29c-eec1dbf78706)

**Comment by LiaNdrY** [comment]
@amrshaheen61

Do you have any multilingual game on UE? Take two different language files, English and some other one. Save the one that is not English and try switching to it in the game. You will have English.

Here are two fades for testing, but without playing they are useless.
https://drive.google.com/file/d/1EZZb80BeUSR2dFL_KfutWyRnhEMDG9tG/view

**Comment by amrshaheen61** [comment]
In this case, I do not use the English language but use any other language.

**Comment by LiaNdrY** [comment]
@amrshaheen61

![image](https://github.com/amrshaheen61/UE4LocalizationsTool/assets/35012888/3c65604a-8830-4614-91cd-a8719189a1a8)

**Comment by LiaNdrY** [comment]
@amrshaheen61

As I understand it, all these different values are crc32

**Comment by amrshaheen61** [comment]
@LiaNdrY 
SourceStringHash=> Text Value hash
this is not an error

**Comment by LiaNdrY** [comment]
@amrshaheen61
Okay, then why do I take the old version of the program 2.3 and do exactly the same thing and I get two identical files and everything works?

**Comment by LiaNdrY** [comment]
@amrshaheen61
The UE is tightly bound to crc32, it does not look at namespace::key when loading localization, searches strictly for crc32, and if it does not find the values it needs, it is loaded from the main localization file - that is, the English localization file.

**Comment by amrshaheen61** [comment]
@LiaNdrY 
In version 2.3, it only changes the SourceString while keeping the header the same
-------
this file use CityHash64 not crc32

**Comment by LiaNdrY** [comment]
@amrshaheen61
That's right, the crc32 values do not change, hence there is no problem. If they change in version 2.4 beta, then they are not calculated correctly.

**Comment by amrshaheen61** [comment]
test this
[Game_NEW.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/12693032/Game_NEW.zip)

**Comment by LiaNdrY** [comment]
@amrshaheen61
My game does not open with this file and the program cannot read it. Take the latest files that I gave you for experimentation.
https://drive.google.com/file/d/1EZZb80BeUSR2dFL_KfutWyRnhEMDG9tG/view?usp=drive_link

**Comment by amrshaheen61** [comment]
@LiaNdrY 
i think you test the last version, worked?

**Comment by LiaNdrY** [comment]
@amrshaheen61
I tried to add a new row, but when I fill in the fields and click the "Add" button, the notification "NameSpace or Key or Value is empty" appears; if I click on the "C" button, the error "An object reference" appears for "NameSpace" or "Key" does not point to an instance of the object."

**Comment by LiaNdrY** [comment]
@amrshaheen61
You also export the csv file incorrectly. Example:

The original contains the line: (Including quotes)
**"So cold. So dark. Help me! Protect me!"**

When exporting to CSV you should get a line like this:
**"""So cold. So dark. Help me! Protect me!"""**

And it turns out like this:
**""So cold. So dark. Help me! Protect me!""**

Another example:

The original contains the line: (Including quotes)
**Typical research time: {0}<img id="Hourglass"/>**

When exporting to CSV you should get a line like this:
**"Typical research time: {0}<img id=""Hourglass""/>"**

And it turns out like this:
**"Typical research time: {0}<img id="Hourglass"/>"**

All this causes errors during import.
