### ISSUE TITLE
Could you add the csv export/import option to command line usage?

### ISSUE THREAD

**Issue by enarkay** [amrshaheen61/UE4LocalizationsTool#43]
Just like the title says, I believe currently you can only use txt format for command line usage.
Could you add the option to use csv format in command line usage in addition?

**Comment by amrshaheen61** [comment]
@enarkay 
export only
import will take a lot of work
[UE4localizationsTool.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/12683570/UE4localizationsTool.zip)

**Comment by KASaLEX-2020** [comment]
Which command to use to start in CSV export via command line?

**Comment by amrshaheen61** [comment]
@KASaLEX-2020 
-c
