### ISSUE TITLE
The data in the Game.locres file is lost after saving.

### ISSUE THREAD

**Issue by iswinnime** [amrshaheen61/UE4LocalizationsTool#52]
[Game.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/13932615/Game.zip)

The file had 91,641 lines before the modification, but after saving, it becomes 91,503 lines, resulting in the loss of some data. Thank you for your efforts, and I wish you a pleasant life as well.

**Comment by TheDarkness1994** [comment]
> [Game.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/13932615/Game.zip)
> 
> The file had 91,641 lines before the modification, but after saving, it becomes 91,503 lines, resulting in the loss of some data. Thank you for your efforts, and I wish you a pleasant life as well.

Can you send a modified file with missing lines? I'll see the differences.

**Comment by isme99** [comment]
Thank you for your response. If you save the "game.loces" file as a new file without making any modifications, some data will be lost. Attached is the file that I saved without making any changes, and as a result, some data was lost.
[Game_NEW.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/13934428/Game_NEW.zip)

**Comment by isme99** [comment]
> > [游戏.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/13932615/Game.zip)
> > 修改前文件有91641行，保存后变成91503行，导致部分数据丢失。感谢您的努力，也祝您生活愉快。
> 
> 您可以发送一个缺少行的修改后的文件吗？我会看到差异。

Thank you for your response. If you save the "game.loces" file as a new file without making any modifications, some data will be lost. Attached is the file that I saved without making any changes, and as a result, some data was lost.
[Uploading Game_NEW.zip…]()

**Comment by TheDarkness1994** [comment]
![image](https://github.com/amrshaheen61/UE4LocalizationsTool/assets/52470097/ef9f4ba4-974d-43c9-8f92-621e585a7fb2)
Have you tried different versions of the program? Perhaps it will help. Here is a screenshot that shows where the change began and the breakdown itself. In the right screenshot you can see that it started with the fact that (Namespace), where the symbols "::" are found, everything is simply erased. Throughout the file. If you are interested, I used the utility ([UE4TextExtractor](https://github.com/VD42/UE4TextExtractor)) to export text where errors are visible.

**Comment by isme99** [comment]
> ![图像](https://private-user-images.githubusercontent.com/52470097/296645966-ef9f4ba4-974d-43c9-8f92-621e585a7fb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyOTE0OTcsIm5iZiI6MTcwNTI5MTE5NywicGF0aCI6Ii81MjQ3MDA5Ny8yOTY2NDU5NjYtZWY5ZjRiYTQtOTc0ZC00M2M5LThmOTItNjIxZTU4NWE3ZmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDAzNTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZGM3NzExNzhlOGIxMjBhNDdiOTM0NDczOTc0YTQ2ZmUyYWZkZDcwYzA1NmU1N2VhZDU5ZjRhZmE1MWFmZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DcyPsdkaX5WMjT-rnA6gG1vdUvuqD5JUgnSTUjhZ2ME) 您是否尝试过该程序的不同版本？也许会有帮助。这是一个屏幕截图，显示了更改开始的位置以及故障本身。在右侧的屏幕截图中，您可以看到它始于这样一个事实：（命名空间），其中找到符号“::”，所有内容都被简单地删除了。贯穿整个文件。如果您有兴趣，我使用实用程序 ( [UE4TextExtractor](https://github.com/VD42/UE4TextExtractor) ) 导出可见错误的文本。

 Thank you for your patient response, which has given me a deeper understanding of this issue. I have tried using earlier versions, but the same problem persists. I will make further adjustments and attempt to resolve it. Thank you for your reply, and I wish you a pleasant life.

**Comment by isme99** [comment]
> ![image](https://private-user-images.githubusercontent.com/52470097/296645966-ef9f4ba4-974d-43c9-8f92-621e585a7fb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyOTE2NzksIm5iZiI6MTcwNTI5MTM3OSwicGF0aCI6Ii81MjQ3MDA5Ny8yOTY2NDU5NjYtZWY5ZjRiYTQtOTc0ZC00M2M5LThmOTItNjIxZTU4NWE3ZmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA0MDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMWI2N2UwYTQ2OGZjYjBiODY1OGRjOTUyMmZiZWZhNmUyMzIwYzhlOGYzMTlkYzBhZmY4NWNjNmMzM2IzNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Amdel8hBziXfojI9A62jDXC2TfOnk1o8s2MAlL3Y8SM) Have you tried different versions of the program? Perhaps it will help. Here is a screenshot that shows where the change began and the breakdown itself. In the right screenshot you can see that it started with the fact that (Namespace), where the symbols "::" are found, everything is simply erased. Throughout the file. If you are interested, I used the utility ([UE4TextExtractor](https://github.com/VD42/UE4TextExtractor)) to export text where errors are visible.

 Thank you for your patient response, which has given me a deeper understanding of this issue. I have tried using earlier versions, but the same problem persists. I will make further adjustments and attempt to resolve it. Thank you for your reply, and I wish you a pleasant life.
