### ISSUE TITLE
Subverse #2

### ISSUE THREAD

**Issue by TheDarkness1994** [amrshaheen61/UE4LocalizationsTool#6]
Hello. Thank you for answering the last issue and updating, even though it was not related to my game, I hope in a future version you will be able to edit such text. But I found another text that looks different and I would also like to change it through your program, but so far there is no such possibility.

**Text:**
_Adaptive Language Learning (A.L.L.)
APEX Industries
Archives, The Imperium
Assie
Azzorion, Lord
Bacchus
Battle of Nü Vegas, The_
and etc.

**Screenshots:**
Text in hex editor:
![image](https://user-images.githubusercontent.com/52470097/171002356-f75dabc7-2bc4-4e08-89cd-778a14417fc8.png)
Text in game:
![Subverse-Win64-Shipping_2022_05_30_16_32_39_712](https://user-images.githubusercontent.com/52470097/171003974-42a425ad-e241-441e-bb7a-be2744aa2c71.png)
File in your program (latest version):
![image](https://user-images.githubusercontent.com/52470097/171003382-a6750e4d-7a78-4f86-a1da-35212029f0dd.png)

Files:
[Codex.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/8798718/Codex.zip)

**Comment by amrshaheen61** [comment]
@TheDarkness1994 
Change edit by hex editor to make sure

**Comment by amrshaheen61** [comment]
@TheDarkness1994 
Change it by hex editor to make sure

**Comment by amrshaheen61** [comment]
@TheDarkness1994 
any news?

**Comment by TheDarkness1994** [comment]
> @TheDarkness1994 any news?

I'm sorry. A new version of the game was released on Steam, I had to deal with new files, I didn’t sleep for two days. Now I'll write what's what

**Comment by TheDarkness1994** [comment]
New version files:
[Codex.zip](https://github.com/amrshaheen61/UE4LocalizationsTool/files/8824122/Codex.zip)

**Comment by TheDarkness1994** [comment]
I tried to change only one word with another program, that's what happened.
![image](https://user-images.githubusercontent.com/52470097/171638437-cb90066e-5035-4d85-9b54-0ed8a740860f.png)
![image](https://user-images.githubusercontent.com/52470097/171638491-7f40fa64-d9c3-45e2-b98c-62ef39b21ec2.png)
I only changed one word:
English
_Adaptive Language Learning (A.L.L.)_
Russian
_Адаптивное Изучение Языков (А.И.Я)_

**Comment by TheDarkness1994** [comment]
> @TheDarkness1994 Try new version [V1.4](https://github.com/amrshaheen61/UE4LocalizationsTool/releases/tag/v1.4) Close the issue if your problem fixed

Thank you very much. Everything works well.
