### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by PieLike** [amrshaheen61/UE4LocalizationsTool#7]
Hello.
Dear amrshaheen61, is it possible to add sorting by name or other, it would be so cool and convenient.

**Comment by amrshaheen61** [comment]
@PieLike 
I will add it in next version

**Comment by amrshaheen61** [comment]
@PieLike 
Done [v1.4](https://github.com/amrshaheen61/UE4LocalizationsTool/releases/tag/v1.4)
