### ISSUE TITLE
Can you add a option to export a txt/json file with "Name" and Text Value?

### ISSUE THREAD

**Issue by KomiksPL** [amrshaheen61/UE4LocalizationsTool#8]
Like "Ablity_Bomb+_Desc": "Unlock the ability to create two bombs at one time"

**Comment by amrshaheen61** [comment]
@KomiksPL 
Okay

**Comment by amrshaheen61** [comment]
@KomiksPL 
Done [v1.4](https://github.com/amrshaheen61/UE4LocalizationsTool/releases/tag/v1.4) , but for txt file only

**Comment by KomiksPL** [comment]
@amrshaheen61 Thanks, I can make my program to conver this to json but very very thanks

**Comment by amrshaheen61** [comment]
@KomiksPL 
You are welcome
